#!/usr/bin/env bash
# Builds each service's own environment file from the platform .env, so
# the operator edits one file and nothing else.
#
# Two files are produced:
#
#   services/work-item-service/.env — generated in full, every run. Its
#     PostgreSQL, Redis and Django settings all come from the platform
#     .env or from scripts/startup/env-contract.sh's defaults. Docker
#     Compose reads this same file twice: as the services' env_file, and
#     as the interpolation source for the ${PGUSER}/${PGPASSWORD}/
#     ${PGDATABASE} references in that stack's docker-compose.yml.
#
#     It also carries every configured JIRA_*_FIELD_ID (workitems/
#     jira_interpret.py and workitems/webhook_consumer.py both read these
#     via os.environ — Story schema fields, the five-field Release schema
#     BUGFIXES.md BF-01 added, and the Agent/Blocked fields). These are
#     genuinely optional — a local-mode-only deployment never sets them —
#     so each is copied from the platform .env only when set there; an
#     unset one is left out of the generated file entirely rather than
#     written empty, same as an unset one is absent from .env itself.
#
#   services/scrummaster/.env — updated in place, never rewritten, since
#     scripts/create-jira-fields.sh and scripts/init-project.sh both write
#     their own values there. Only the keys this flow owns are set.
#
#     AI_GANG_HOME is the one that matters most: ScrumMaster's compose file
#     resolves /projects and /agent-docs from ${AI_GANG_HOME:-$HOME/ai-gang},
#     and the daemon evaluates that path on the host. Left unset, the
#     daemon would create two empty directories and ScrumMaster would come
#     up healthy and blind — able to see neither the project workspaces it
#     searches for BLOCKED markers nor the agent definitions it validates
#     paths against.
#
# Both derived files carry secrets copied from .env, and both are ignored
# by git (the repository's .gitignore ignores .env at every level). They
# are written 0600.

set -euo pipefail

STARTUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$STARTUP_DIR/lib.sh"

WIS_DIR="$AIGANG_ROOT/services/work-item-service"
SM_DIR="$AIGANG_ROOT/services/scrummaster"

# Every JIRA_*_FIELD_ID workitems/jira_interpret.py and
# workitems/webhook_consumer.py read via os.environ (grepped from both —
# see this file's header comment). Reuses the SAME env var names
# services/scrummaster/src/jira.js already reads, per jira_interpret.py's
# own module docstring, so one .env can configure both services'
# custom-field ids identically.
JIRA_FIELD_ID_VARS=(
  JIRA_AGENT_FIELD_ID
  JIRA_BLOCKED_FIELD_ID
  JIRA_VALUE_HYPOTHESIS_FIELD_ID
  JIRA_TEST_MEASUREMENT_FIELD_ID
  JIRA_BEHAVIOR_FIELD_ID
  JIRA_AC_FIELD_ID
  JIRA_CONSTRAINTS_FIELD_ID
  JIRA_EDGE_CASES_FIELD_ID
  JIRA_OUT_OF_SCOPE_FIELD_ID
  JIRA_TARGET_PROJECT_FIELD_ID
  JIRA_RELEASE_NOTES_FIELD_ID
  JIRA_CANDIDATE_SHA_FIELD_ID
  JIRA_BUILD_IDENTIFIER_FIELD_ID
  JIRA_PREVIEW_URL_FIELD_ID
)

# Sets one KEY=value in a file, replacing an existing assignment or
# appending a new one, and leaving every other line untouched.
set_env_var() {
  local file="$1" name="$2" value="$3" tmp
  touch "$file"
  if grep -qE "^[[:space:]]*${name}=" "$file"; then
    tmp="$(mktemp)"
    awk -v name="$name" -v value="$value" '
      $0 ~ "^[[:space:]]*" name "=" { if (!done) { print name "=" value; done = 1 } ; next }
      { print }
      END { if (!done) print name "=" value }
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
  else
    printf '%s=%s\n' "$name" "$value" >> "$file"
  fi
}

# --- work-item service ------------------------------------------------
[[ -d "$WIS_DIR" ]] || die "work-item service directory missing at $WIS_DIR"

WIS_ENV="$WIS_DIR/.env"
WIS_TMP="$(mktemp)"
{
  echo "# Generated by scripts/startup/derive-env.sh from the platform .env."
  echo "# Edit ../../.env and re-run platform startup; edits here are overwritten."
  echo "PGHOST=$(env_value PGHOST)"
  echo "PGPORT=$(env_value PGPORT)"
  echo "PGUSER=$(env_value PGUSER)"
  echo "PGPASSWORD=$(env_value PGPASSWORD)"
  echo "PGDATABASE=$(env_value PGDATABASE)"
  echo "DJANGO_SECRET_KEY=$(env_value DJANGO_SECRET_KEY)"
  echo "REDIS_HOST=ai-gang-redis"
  echo "REDIS_PORT=6379"
  echo "PORT=9100"
  for jira_var in "${JIRA_FIELD_ID_VARS[@]}"; do
    if jira_value="$(env_file_get "$AIGANG_ENV_FILE" "$jira_var")" && [[ -n "$jira_value" ]]; then
      printf '%s=%s\n' "$jira_var" "$jira_value"
    fi
  done
} > "$WIS_TMP"
chmod 600 "$WIS_TMP"
mv "$WIS_TMP" "$WIS_ENV"
chmod 600 "$WIS_ENV"
log "wrote $WIS_ENV"

# --- ScrumMaster -------------------------------------------------------
[[ -d "$SM_DIR" ]] || die "ScrumMaster directory missing at $SM_DIR"

SM_ENV="$SM_DIR/.env"
if [[ ! -f "$SM_ENV" ]]; then
  if [[ -f "$SM_DIR/.env.example" ]]; then
    cp "$SM_DIR/.env.example" "$SM_ENV"
    log "created $SM_ENV from .env.example"
  else
    : > "$SM_ENV"
    log "created empty $SM_ENV"
  fi
fi
chmod 600 "$SM_ENV"

set_env_var "$SM_ENV" AI_GANG_HOME "$AIGANG_ROOT"
set_env_var "$SM_ENV" REDIS_HOST ai-gang-redis
set_env_var "$SM_ENV" REDIS_PORT 6379
set_env_var "$SM_ENV" PORT 9000
log "set AI_GANG_HOME=$AIGANG_ROOT in $SM_ENV"
