# Generated by Django 5.0.14 on 2026-09-20 04:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repository', models.TextField()),
                ('path', models.TextField()),
                ('requested_by', models.TextField()),
                ('task_id', models.TextField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artifact', models.ForeignKey(db_column='artifact_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='artifacts.artifact')),
            ],
            options={
                'db_table': 'artifact_delivery',
                'indexes': [models.Index(fields=['repository'], name='idx_artifact_delivery_repo')],
            },
        ),
        migrations.AddConstraint(
            model_name='artifactdelivery',
            constraint=models.UniqueConstraint(fields=('artifact', 'repository'), name='uniq_artifact_delivery_pair'),
        ),
    ]
