# Generated by Django 5.0.14 on 2026-09-20 03:34

import artifacts.storage
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(db_column='path', max_length=255, storage=artifacts.storage.artifact_storage, upload_to=artifacts.storage.upload_to)),
                ('original_filename', models.TextField(blank=True)),
                ('uploaded_by', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'artifact',
                'indexes': [models.Index(fields=['created_at'], name='idx_artifact_created')],
            },
        ),
        migrations.CreateModel(
            name='ArtifactAccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.TextField()),
                ('artifact_id', models.UUIDField(blank=True, null=True)),
                ('actor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artifact_access_log',
                'indexes': [models.Index(fields=['occurred_at'], name='idx_artifact_access_occurred')],
            },
        ),
    ]
