# Generated by Django 5.0.14 on 2026-09-07 14:19

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('project', models.TextField(primary_key=True, serialize=False)),
                ('mode', models.TextField(choices=[('local', 'Local'), ('jira', 'Jira')], default='local')),
                ('jira_project_key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'project_config',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
                ('status', models.TextField()),
                ('baseline_status', models.TextField()),
                ('jira_status_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_status_config',
            },
        ),
        migrations.CreateModel(
            name='WebhookFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('work_item_id', models.UUIDField(blank=True, null=True)),
                ('external_key', models.TextField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'webhook_failure',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('external_key', models.TextField(blank=True, null=True, unique=True)),
                ('type', models.TextField()),
                ('display_name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('assignee_agent_id', models.TextField(blank=True, db_column='assignee_agent_id', null=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('writes_files', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('writes_services', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('project', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'work_item',
            },
        ),
        migrations.CreateModel(
            name='WorkItemArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.TextField()),
                ('reference', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'work_item_artifact',
            },
        ),
        migrations.CreateModel(
            name='WorkItemComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('body', models.TextField()),
                ('reference_file', models.TextField(blank=True, null=True)),
                ('reference_function', models.TextField(blank=True, null=True)),
                ('source_message_id', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'work_item_comment',
            },
        ),
        migrations.CreateModel(
            name='WorkItemHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.TextField()),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('actor', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'work_item_history',
            },
        ),
        migrations.CreateModel(
            name='WorkItemLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'work_item_link',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.TextField()),
                ('project', models.TextField(blank=True, null=True)),
                ('work_item_id', models.UUIDField(blank=True, null=True)),
                ('actor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'access_log',
                'indexes': [models.Index(fields=['occurred_at'], name='idx_access_log_occurred')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('event_type', models.TextField()),
                ('work_item_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('stream_entry_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_event',
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['created_at'], name='idx_outbox_unpublished')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectconfig',
            constraint=models.CheckConstraint(check=models.Q(('mode__in', ['local', 'jira'])), name='ck_project_config_mode'),
        ),
        migrations.AddConstraint(
            model_name='projectstatusconfig',
            constraint=models.UniqueConstraint(fields=('project', 'status'), name='pk_project_status_config'),
        ),
        migrations.AddIndex(
            model_name='webhookfailure',
            index=models.Index(fields=['work_item_id'], name='idx_webhook_failure_item'),
        ),
        migrations.AddIndex(
            model_name='webhookfailure',
            index=models.Index(fields=['occurred_at'], name='idx_webhook_failure_occurred'),
        ),
        migrations.CreateModel(
            name='WorkItemStoryDetail',
            fields=[
                ('work_item', models.OneToOneField(db_column='work_item_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='story_detail', serialize=False, to='workitems.workitem')),
                ('behavior', models.TextField()),
                ('acceptance_criteria', models.TextField()),
                ('constraints', models.TextField()),
                ('edge_cases', models.TextField()),
                ('out_of_scope', models.TextField()),
                ('value_hypothesis', models.TextField(blank=True, null=True)),
                ('test_measurement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'work_item_story_detail',
            },
        ),
        migrations.AddField(
            model_name='workitem',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='workitems.workitem'),
        ),
        migrations.AddField(
            model_name='workitemartifact',
            name='work_item',
            field=models.ForeignKey(db_column='work_item_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='artifacts', to='workitems.workitem'),
        ),
        migrations.AddField(
            model_name='workitemcomment',
            name='work_item',
            field=models.ForeignKey(db_column='work_item_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='workitems.workitem'),
        ),
        migrations.AddField(
            model_name='workitemhistory',
            name='work_item',
            field=models.ForeignKey(db_column='work_item_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='workitems.workitem'),
        ),
        migrations.AddField(
            model_name='workitemlink',
            name='from_work_item',
            field=models.ForeignKey(db_column='from_work_item_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='links_from', to='workitems.workitem'),
        ),
        migrations.AddField(
            model_name='workitemlink',
            name='to_work_item',
            field=models.ForeignKey(db_column='to_work_item_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='links_to', to='workitems.workitem'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['project', 'status'], name='idx_work_item_project_status'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(condition=models.Q(('parent__isnull', False)), fields=['parent'], name='idx_work_item_parent'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(condition=models.Q(('assignee_agent_id__isnull', False)), fields=['assignee_agent_id'], name='idx_work_item_assignee'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', [0, 1, 2, 3, 4])), name='ck_work_item_priority'),
        ),
        migrations.AddIndex(
            model_name='workitemartifact',
            index=models.Index(fields=['work_item'], name='idx_work_item_artifact_item'),
        ),
        migrations.AddIndex(
            model_name='workitemcomment',
            index=models.Index(fields=['work_item', 'created_at'], name='idx_work_item_comment_item'),
        ),
        migrations.AddIndex(
            model_name='workitemhistory',
            index=models.Index(fields=['work_item', 'occurred_at'], name='idx_work_item_history_item'),
        ),
        migrations.AddIndex(
            model_name='workitemlink',
            index=models.Index(fields=['from_work_item', 'link_type'], name='idx_work_item_link_from'),
        ),
        migrations.AddIndex(
            model_name='workitemlink',
            index=models.Index(fields=['to_work_item', 'link_type'], name='idx_work_item_link_to'),
        ),
        migrations.AddConstraint(
            model_name='workitemlink',
            constraint=models.UniqueConstraint(fields=('from_work_item', 'to_work_item', 'link_type'), name='idx_work_item_link_unique'),
        ),
    ]
