# Generated by Django 5.0.14 on 2026-09-20 04:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        ('workitems', '0004_normalize_blank_external_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemSpecificationLink',
            fields=[
                ('work_item', models.OneToOneField(db_column='work_item_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specification_link', serialize=False, to='workitems.workitem')),
                ('requirement_id', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artifact', models.ForeignKey(db_column='artifact_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='artifacts.artifact')),
            ],
            options={
                'db_table': 'work_item_specification_link',
            },
        ),
        migrations.CreateModel(
            name='WorkItemArtifactLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artifact', models.ForeignKey(db_column='artifact_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='artifacts.artifact')),
                ('work_item', models.ForeignKey(db_column='work_item_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='artifact_links', to='workitems.workitem')),
            ],
            options={
                'db_table': 'work_item_artifact_link',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['work_item', 'position'], name='idx_wi_artifact_link_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='workitemartifactlink',
            constraint=models.UniqueConstraint(fields=('work_item', 'artifact'), name='idx_wi_artifact_link_unique'),
        ),
        migrations.AddIndex(
            model_name='workitemspecificationlink',
            index=models.Index(fields=['artifact', 'requirement_id'], name='idx_wi_spec_link_artifact_req'),
        ),
    ]
