# Generated by Django 5.0.14 on 2026-10-04 02:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0005_work_item_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaDeploymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('deployed_sha', models.TextField()),
                ('build_identifier', models.TextField()),
                ('build_url', models.TextField(blank=True, null=True)),
                ('beta_url', models.TextField(blank=True, null=True)),
                ('source_message_id', models.TextField(blank=True, null=True)),
                ('work_item_ids', models.JSONField(default=list)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'beta_deployment_record',
            },
        ),
        migrations.CreateModel(
            name='JiraWriteCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_key', models.TextField()),
                ('work_item_id', models.UUIDField()),
                ('step', models.TextField()),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jira_write_completion',
            },
        ),
        migrations.AddIndex(
            model_name='workitemartifact',
            index=models.Index(fields=['artifact_type', 'reference'], name='idx_work_item_artifact_ref'),
        ),
        migrations.AddIndex(
            model_name='betadeploymentrecord',
            index=models.Index(fields=['recorded_at'], name='idx_beta_deployment_recorded'),
        ),
        migrations.AddConstraint(
            model_name='betadeploymentrecord',
            constraint=models.UniqueConstraint(fields=('deployed_sha', 'build_identifier'), name='uq_beta_deployment_sha_build'),
        ),
        migrations.AddIndex(
            model_name='jirawritecompletion',
            index=models.Index(fields=['registered_at'], name='idx_jira_write_completion_age'),
        ),
        migrations.AddConstraint(
            model_name='jirawritecompletion',
            constraint=models.UniqueConstraint(fields=('completion_key', 'work_item_id', 'step'), name='uq_jira_write_completion_step'),
        ),
    ]
