# Generated by Django 5.0.14 on 2026-10-04 13:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0006_v52_canonical_delivery_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraDecompositionProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('parent_work_item_id', models.UUIDField(blank=True, null=True)),
                ('proposal_id', models.UUIDField()),
                ('jira_key', models.TextField(blank=True, null=True)),
                ('specification_link', models.JSONField(blank=True, null=True)),
                ('artifact_links', models.JSONField(default=list)),
                ('blocks_pairs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'jira_decomposition_proposal',
                'indexes': [models.Index(fields=['jira_key'], name='idx_jira_decomposition_key'), models.Index(fields=['project'], name='idx_jira_decomposition_project')],
            },
        ),
        migrations.AddConstraint(
            model_name='jiradecompositionproposal',
            constraint=models.UniqueConstraint(fields=('proposal_id',), name='uq_jira_decomposition_proposal'),
        ),
    ]
